### PR TITLE
design-done

### PR DESCRIPTION
**Pull request by ananyaa07**
Issue: 8

image

### CODE REVIEW

**Comment by Saishreekouda** [comment]
Hey @ananyaa07, 
You do not have to make a dashboard. You just have to make a normal leaderboard that will be same for every viewer not user specific. You can just take the leaderboard section from this and improve that and remove rest of the elements. You can ping me on discord for any doubts.

**Comment by ananyaa07** [comment]
@Saishreekouda We could just replace the name with the word contributor , in that case it will become same for every user

**Comment by Saishreekouda** [comment]
@ananyaa07 Yes but all of that is unnecessary, we just want to show the leaderboard. You can highlight the first, second and third position and the other contributors in the list.

**Comment by ananyaa07** [comment]
image

@Saishreekouda is it okay now?

**Pull request merged**
