### PR TITLE
Issue 14

### PR DESCRIPTION
**Pull request by abhinavs1920**
Issue: 14

#### Short description of what this resolves:
It gives responsive titles and images to the leaderboard webpage

#### Changes proposed in this pull request and/or Screenshots(if applicable):

- Title Added
- Opencode and Geekhaven Symbol added
Screenshot_20221229_112059

### CODE REVIEW

**Comment by Mudit018** [comment]
@abhinavs1920 Provide a live link to website

**Comment by abhinavs1920** [comment]
How ?? you can download my code and run it on your own system

**Comment by Mudit018** [comment]
You can deploy your forked repo on github pages and then send me the linked to view it. And yes I can download the code and run it on my system but see the thing is that I am not only managing issues in this repository but I have to manage issues in CollabWeb-2022 also and then I need to do a let of work, so I don't have that much time to download your code. Its better that you provide what I am asking and I will merge your PR.

**Comment by abhinavs1920** [comment]
https://abhinavs1920.github.io/Leaderboard/

**Pull request merged**
